### ISSUE TITLE
Special character such as '+' in SQL is not properly encoded

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/dashboard#104]
Refer to https://github.com/GreptimeTeam/greptimedb/issues/941

**Comment by DiamondMofeng** [comment]
In the latest docker image:

![图片](https://user-images.githubusercontent.com/52260316/216740864-3fbf0fc1-0670-4b01-a938-bf38be5ae7ac.png)


![图片](https://user-images.githubusercontent.com/52260316/216740836-5bb3de35-5d2d-4871-b146-c66b15dbaf65.png)

**Comment by ZonaHex** [comment]
This is related to PR #93 
Not finished yet.
