### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by shuiyisong** [GreptimeTeam/dashboard#140]
Binding some shortcuts to certain function(button) may help increase user experience.

E.g: `cmd+enter` for "Run Current Line(SQL)"

<img width="1799" alt="image" src="https://user-images.githubusercontent.com/113876041/220570139-6e3eb607-664c-4c24-a9ec-73e72f972503.png">

**Comment by alili** [comment]
```
const defaultKeymap = [
    {
      key: 'alt-Enter',
      run: () => {
        runQueryAll()
      },
    },
    {
      key: 'ctrl-Enter',
      run: () => {
        runPartQuery()
      },
    },
  ]
```

In the latest version, Two shortcut keys have been added, each supporting runQueryAll & runQueryInline
