### ISSUE TITLE
Inject `VITE_CLOUD_URL` at runtime

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/dashboard#158]
We need to seek a further solution to inject `VITE_CLOUD_URL` at runtime so we can reuse same image across different environments. Let me create an issue for this.

_Originally posted by @sunng87 in https://github.com/GreptimeTeam/dashboard/pull/156#pullrequestreview-1325479339_

**Comment by ZonaHex** [comment]
I don't think we could use the same image for dev and staging.
We could edit the action YML and make sure the commit sha for the staging image is (one of) the latest sha for the dev image (already tested).
