### ISSUE TITLE
Commented SQL won't be ignored when "Run All"

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/dashboard#19]
## To reproduce

I write this in the dashboard editor
```sql
-- This is a comment
show tables;
```
and click "Run All", then get this error:
```
Error: Query engine output error: Failed to execute query: -- This is a comment show tables;, source: Invalid SQL, error: Currently executing multiple SQL queries are not supported.
```
Looks like the comment doesn't get ignored.

## Expected behavior
It should run correctly as there is no comment content.

## Screenshot
<img width="1243" alt="图片" src="https://user-images.githubusercontent.com/15380403/205203988-d8ff6a0c-1e23-46bb-b2ef-7223a806928c.png">

**Comment by sunng87** [comment]
This is related to https://github.com/GreptimeTeam/greptimedb/issues/468

For now, our sql apis accepts sql input as string but doesn't have multiple statement support.
