### ISSUE TITLE
The table keeps rolling and crash when there are columns that might need collapsing

### ISSUE THREAD

**Issue by 0neSe7en** [GreptimeTeam/dashboard#452]
The `event` column in this case is JSON type.

If multiple columns need collapsing, it can be worse and will crash the app.

https://github.com/user-attachments/assets/3add5bb9-8fc4-438e-9053-e3150275e945

Greptime 0.9.5

**Comment by ZonaHex** [comment]
Thanks! Will work on this ASAP :)

**Comment by ZonaHex** [comment]
@0neSe7en Hi again! After taking a furthur look, I believe this issue has been resolved in the [latest version](https://github.com/GreptimeTeam/dashboard/releases/tag/v0.6.0) of dashboard. GreptimeDB v0.9.5 carried the older version of dashboard, and will be updated in the next version. If you are interested, you could try [dashboard's latest docker.](https://github.com/GreptimeTeam/dashboard?tab=readme-ov-file#with-docker)
Sorry for the user experience. You are more than welcome to reopen this or open another issue if there's any other problem that I may have missed.

**Comment by 0neSe7en** [comment]
Hi @ZonaHex , yeah I can confirm that this issue has been resolved in the latest version. Thanks
