### ISSUE TITLE
Fields not displayed correctly when viewing detailed information of a log with JSON fields on the "Log Query" page

### ISSUE THREAD

**Issue by zzzdong** [GreptimeTeam/dashboard#469]
## Description:

In the Log Query page, when I click on a log entry that contains JSON fields to view its detailed information, the Fields section on the right side does not display the fields correctly.

## Temporary Fix:

I have made a simple fix for this issue, which you can find in the following commit:

[Commit Link](https://github.com/GreptimeTeam/dashboard/commit/90feee78f885fc65d14a9b439963c1aeafb0f54f)

If this fix is acceptable, I would be happy to submit a pull request to address this issue.

**Comment by sunchanglong** [comment]
@zzzdong  it looks good,I noted a small comment.
